// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _31Aug2017UpdateWhoKnows4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_31Aug2017UpdateWhoKnows4));
        
        string IMigrationMetadata.Id
        {
            get { return "201708310517266_31-Aug-2017UpdateWhoKnows4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
