// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _30Aug2017Test23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30Aug2017Test23));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300602405_30-Aug-2017Test23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
