// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update3d : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update3d));
        
        string IMigrationMetadata.Id
        {
            get { return "201708030621135_Update3d"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
