<<<<<<< Updated upstream:ProgramPlanner/ProgramPlanner/Migrations/201708300610145_30-Aug-2017Test24.Designer.cs
// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _30Aug2017Test24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30Aug2017Test24));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300610145_30-Aug-2017Test24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
=======
// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _27Aug20161 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27Aug20161));
        
        string IMigrationMetadata.Id
        {
            get { return "201708270536466_27-Aug-2016-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
>>>>>>> Stashed changes:ProgramPlanner/ProgramPlanner/Migrations/201708270536466_27-Aug-2016-1.Designer.cs
