// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update3i : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update3i));
        
        string IMigrationMetadata.Id
        {
            get { return "201708040626597_Update3i"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
