<<<<<<< Updated upstream:ProgramPlanner/ProgramPlanner/Migrations/201708300308322_30-Aug-2017Test13.Designer.cs
// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _30Aug2017Test13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30Aug2017Test13));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300308322_30-Aug-2017Test13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
=======
// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test45 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test45));
        
        string IMigrationMetadata.Id
        {
            get { return "201708270417157_test45"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
>>>>>>> Stashed changes:ProgramPlanner/ProgramPlanner/Migrations/201708270417157_test45.Designer.cs
