// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _27Aug20161 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27Aug20161));
        
        string IMigrationMetadata.Id
        {
            get { return "201708270536466_27-Aug-2016-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
