<<<<<<< Updated upstream:ProgramPlanner/ProgramPlanner/Migrations/201708310259346_31-Aug-2017Update6.Designer.cs
// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _31Aug2017Update6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_31Aug2017Update6));
        
        string IMigrationMetadata.Id
        {
            get { return "201708310259346_31-Aug-2017Update6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
=======
// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _27Aug20173 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27Aug20173));
        
        string IMigrationMetadata.Id
        {
            get { return "201708270616143_27-Aug-2017-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
>>>>>>> Stashed changes:ProgramPlanner/ProgramPlanner/Migrations/201708270616143_27-Aug-2017-3.Designer.cs
