// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _12Aug2017Update14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12Aug2017Update14));
        
        string IMigrationMetadata.Id
        {
            get { return "201708120600018_12-Aug-2017Update14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
