<<<<<<< Updated upstream:ProgramPlanner/ProgramPlanner/Migrations/201708280351085_Test100.Designer.cs
// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Test100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test100));
        
        string IMigrationMetadata.Id
        {
            get { return "201708280351085_Test100"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
=======
// <auto-generated />
namespace ProgramPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test43 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test43));
        
        string IMigrationMetadata.Id
        {
            get { return "201708270426109_test43"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
>>>>>>> Stashed changes:ProgramPlanner/ProgramPlanner/Migrations/201708270426109_test43.Designer.cs
